language: perl
perl:
  - "5.10.1"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "blead"
matrix:
  include:
    - perl: "5.20.0"
      env: COVERAGE=1
before_install:
  - export DIST_INKT_PROFILE="Dist::Inkt::Profile::TOBYINK"
  - git clone git://github.com/haarg/perl-travis-helper
  - source perl-travis-helper/init
  - build-perl
  - perl -V
  - build-dist
  - cd $BUILD_DIR
install:
  - cpan-install --toolchain
  - cpan-install --deps
  - cpan-install --coverage
before_script:
  - coverage-setup
script:
  - prove -l $(test-dirs)
after_success:
  - coverage-report

